apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-v1
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
      version: v1
  template:
    metadata:
      labels:
        app: playground
        version: v1
    spec:
      containers:
      - name: playground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground-v1
  namespace: dev
spec:
  selector:
    app: playground
    version: v1
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer